### ISSUE TITLE
controllo di tutti i file in una cartella

### ISSUE THREAD

**Issue by Flecart** [csunibo/filenames-linter#14]
Creazione di una funzione che controlla tutti i file in una cartella in go.

Sintassi tipo:

`[nomeprogramma] check <nomefile.synta> <nomedir>` 

Deve ritornare errore sul file che non soddisfano
Altrimenti non printa niente.
Magari una flag per dire ritorna tutti gli errori, oppure solo il primo?

**Comment by samuelemusiani** [comment]
Un distastro github

**Comment by lucat1** [comment]
Fatto in #18
